# Site settings
title: Yegor Kolosov
author: Yegor Kolosov
email: kolosov-egor@yandex.ru
description: Ideas, thoughts, projects

# Build settings
remote_theme: riggraz/no-style-please
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme

# Post URL structure
permalink: /post/:title/

# GitHub Pages base URL (site: https://rbpp3042.github.io/my_notes)
baseurl: "/my_notes"
url: "https://rbpp3042.github.io"

# Theme settings
theme_config:
  appearance: "dark"
  back_home_text: "← Home"
  date_format: "%Y-%m-%d"
  show_description: true

# GitHub Pages
github: [metadata]
encoding: UTF-8
kramdown:
  input: GFM
  hard_wrap: false
future: true
jailed: false
gfm_quirks: paragraph_end

