# Настройки сайта
title: Мой новый блог
author: Ваше Имя
email: your-email@example.com
description: >- # Описание вашего блога. Можно написать в несколько строк.
  Здесь я буду делиться своими мыслями, идеями и проектами.

# Настройки сборки
remote_theme: riggraz/no-style-please
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme

# Структура URL для постов (оптимизировано для Telegram Instant View)
permalink: /post/:title/

# Если ваш блог будет в подпапке, например, https://USERNAME.github.io/BLOG_REPO_NAME/
# то раскомментируйте и укажите имя репозитория:
baseurl: "/my_notes"

# Дополнительные настройки темы
theme_config:
  appearance: "auto" # можно изменить на "light" или "dark"
  back_home_text: "← Home"
  date_format: "%d.%m.%Y"
  show_description: true 
