# Настройки сайта
title: Синяя изолента, зубочистки и чатгпт
author: Ваше Имя
email: your-email@example.com
description: Идеи, мысли, проекты

# Настройки сборки
remote_theme: riggraz/no-style-please
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme

# Структура URL для постов
permalink: /post/:title/

# Базовый URL для GitHub Pages
baseurl: "/my_notes"
url: "https://rbpp3042.github.io"

# Дополнительные настройки темы
theme_config:
  appearance: "dark"
  back_home_text: "← Home"
  date_format: "%d.%m.%Y"
  show_description: true

# Настройки GitHub Pages
github: [metadata]
encoding: UTF-8
kramdown:
  input: GFM
  hard_wrap: false
future: true
jailed: false
gfm_quirks: paragraph_end

# Настройки постов
excerpt_separator: "<!-- more -->" 
